general.import = [
    #"~/.config/alacritty/themes/themes/rose_pine.toml"
    #"~/.config/alacritty/themes/themes/omni.toml"
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
term = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"
shape = "Block"

[debug]
print_events = false
render_timer = false

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 5000

[window]
decorations = "None"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
blur = true
startup_mode = "Maximized"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 4		
y = 0

[window.position]
x = 260
y = 250
