# handy ls aliases
alias ppath="echo $PATH | sed 's/:/\n/g'"

alias files="xdg-open"
alias studio="studio.sh 1>/dev/null 2>/dev/null & disown"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias reload=". ~/.bashrc"
alias soff="xset dpms force off"

alias cl="clear && ls"
alias cll="clear && ll"
alias cla="clear && la"

alias sl="ls"
alias ls="eza"
alias la="ls -Ga"
alias ll="ls -lg"
alias lla="ls -lag"
alias llo="ll -o"
alias lsd="ls -D"
alias lsf="ls -f"

alias python="python3"
alias py="python"
alias cd="z"

alias tks="confirm tmux kill-session -t"
alias tns="tmux new -s"
alias tls="tmux ls"
alias tkall="confirm tmux kill-server"
alias tas="tmux a -t"
alias ta="tmux a"
